# Generated by Django 2.2.14 on 2020-07-29 07:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0022_userprofile_userphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressline01', models.CharField(blank=True, max_length=60, null=True)),
                ('addressline02', models.CharField(blank=True, max_length=60, null=True)),
                ('addressline03', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifydate', models.DateTimeField(auto_now=True)),
                ('addresstype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.AddressType')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Country')),
                ('lastmodifyby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.State')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userphoto',
            field=models.ImageField(blank=True, default='profile2.png', null=True, upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryuseraddress', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifydate', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Address')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
