# Generated by Django 2.2.14 on 2020-08-05 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0035_auto_20200804_2223'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useraddress',
            name='unique_useraddress',
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='emailaddress',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='useraddress',
            unique_together={('user', 'address')},
        ),
        migrations.AlterUniqueTogether(
            name='userphone',
            unique_together={('user', 'phone')},
        ),
    ]
