# Generated by Django 2.2.14 on 2020-08-05 03:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0037_auto_20200804_2247'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userphone',
            unique_together={('user', 'primaryuserphone'), ('user', 'phone')},
        ),
    ]
