# Generated by Django 2.2.14 on 2021-01-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengecurriculum',
            name='progressionid',
        ),
    ]
