# Generated by Django 3.1.5 on 2021-02-04 03:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruct', '0002_remove_challengecurriculum_progressionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('curriculumid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruct.curriculum')),
                ('lastmodifyby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentcurriculum_requests_created', to=settings.AUTH_USER_MODEL)),
                ('progressionid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instruct.progression')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
