# Generated by Django 3.1.5 on 2021-02-12 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0003_studentcurriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='answertypeid',
        ),
    ]
