# Generated by Django 3.1.5 on 2021-02-26 02:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruct', '0005_delete_answertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=60)),
                ('displayorder', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifyby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studentcurriculum',
            name='statusid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='instruct.status'),
            preserve_default=False,
        ),
    ]
