# Generated by Django 3.0.7 on 2021-03-05 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruct', '0006_auto_20210225_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='lastmodifydate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='challengecurriculum',
            name='lastmodifydate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='challengetype',
            name='lastmodifydate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='lastmodifydate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='progression',
            name='lastmodifydate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='status',
            name='lastmodifydate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studentcurriculum',
            name='lastmodifydate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='lastmodifyby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='challenge_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challengecurriculum',
            name='lastmodifyby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='challengecurriculum_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='challengetype',
            name='lastmodifyby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='challengetype_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='lastmodifyby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='curriculum_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progression',
            name='lastmodifyby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='progression_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='lastmodifyby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentcurriculum',
            name='lastmodifyby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='studentcurriculum_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
