# Generated by Django 3.1.7 on 2021-03-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0008_auto_20210306_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progression',
            name='displayorder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
