# Generated by Django 3.1.7 on 2021-03-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0009_auto_20210306_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='displayorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengecurriculum',
            name='displayorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengetype',
            name='displayorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='displayorder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='displayorder',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
