# Generated by Django 3.1.7 on 2021-03-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0010_auto_20210324_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='hintsvideo',
            field=models.FileField(upload_to='hintsVideos/'),
        ),
    ]
