# Generated by Django 3.2.5 on 2021-08-05 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0012_studentchallengeevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengecurriculum',
            name='challengeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challengecurriculums', to='instruct.challenge'),
        ),
    ]
