# Generated by Django 3.1.5 on 2022-02-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0013_alter_challengecurriculum_challengeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentchallengeevent',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentchallengeevent',
            name='videofile',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
