# Generated by Django 3.1.5 on 2022-02-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0014_auto_20220201_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='hintsvideo',
            field=models.FileField(blank=True, upload_to='hintsVideos/'),
        ),
    ]
