# Generated by Django 3.2.12 on 2022-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0015_auto_20220209_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='belt',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
