# Generated by Django 3.2.12 on 2022-11-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0016_alter_curriculum_belt'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='allowhomework',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='allowvideorecord',
            field=models.BooleanField(default=False),
        ),
    ]
