# Generated by Django 3.2.12 on 2022-11-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0017_auto_20221122_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='allowvideorecord',
            field=models.BooleanField(default=True),
        ),
    ]
