# Generated by Django 3.2.12 on 2022-11-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruct', '0020_challenge_allowvideorecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='allowhomework',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='allowvideorecord',
        ),
    ]
