# Generated by Django 3.0.7 on 2020-07-01 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_userprofile_lastmodifydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lastmodifyby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modifier', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
