# Generated by Django 2.2.14 on 2020-07-08 02:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_lastmodifyby'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresstype', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifydate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifydate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryexchange', models.CharField(max_length=5)),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifydate', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonetype', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifydate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='securityquestion',
            name='lastmodifyby',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='lastmodifyby',
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifydate', models.DateTimeField(auto_now=True)),
                ('countryexchange', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CountryExchange')),
                ('phonetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.PhoneType')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressline01', models.CharField(max_length=60)),
                ('addressline02', models.CharField(max_length=60)),
                ('addressline03', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('postalcode', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifydate', models.DateTimeField(auto_now=True)),
                ('addresstype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.AddressType')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Country')),
            ],
        ),
    ]
