# Generated by Django 2.2.14 on 2020-07-08 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressline02',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressline03',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postalcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.State'),
        ),
    ]
