# Generated by Django 2.2.14 on 2020-07-29 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200708_0110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
