# Generated by Django 3.0.9 on 2020-09-09 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0042_auto_20200804_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityquestion',
            name='lastmodifyby',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifier', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
