# Generated by Django 2.2.7 on 2020-04-12 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200411_1823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
