# Generated by Django 2.0.10 on 2020-06-24 03:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_securityquestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecurityQuestions',
            new_name='SecurityQuestion',
        ),
    ]
