# Generated by Django 3.0.7 on 2020-07-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_userprofile_userphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityquestion',
            name='lastmodifydate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
