# Generated by Django 3.0.7 on 2020-07-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_securityquestion_lastmodifydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lastmodifydate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
