# Generated by Django 3.0.7 on 2020-12-13 21:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0064_auto_20200909_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=60)),
                ('longname', models.CharField(max_length=255)),
                ('displayorder', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifyby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=60)),
                ('longname', models.CharField(max_length=255)),
                ('displayorder', models.IntegerField()),
                ('hints', models.CharField(blank=True, max_length=255)),
                ('hintsvideo', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('answertypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.AnswerType')),
            ],
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=60)),
                ('longname', models.CharField(max_length=255)),
                ('displayorder', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifyby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=60)),
                ('longname', models.CharField(max_length=255)),
                ('belt', models.CharField(blank=True, max_length=100)),
                ('displayorder', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifyby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('progressionid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Progression')),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=60)),
                ('longname', models.CharField(max_length=255)),
                ('displayorder', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('lastmodifyby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayorder', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('startdate', models.DateTimeField(default=datetime.datetime.now)),
                ('enddate', models.DateTimeField(default=datetime.datetime(2999, 12, 31, 23, 59, 59))),
                ('challengeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Challenge')),
                ('curriculumid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Curriculum')),
                ('lastmodifyby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('progressionid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Progression')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='challengetypeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ChallengeType'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='lastmodifyby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
