# Generated by Django 3.0.7 on 2020-12-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20201213_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='answertypeid',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='challengetypeid',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='lastmodifyby',
        ),
        migrations.RemoveField(
            model_name='challengecurriculum',
            name='challengeid',
        ),
        migrations.RemoveField(
            model_name='challengecurriculum',
            name='curriculumid',
        ),
        migrations.RemoveField(
            model_name='challengecurriculum',
            name='lastmodifyby',
        ),
        migrations.RemoveField(
            model_name='challengecurriculum',
            name='progressionid',
        ),
        migrations.RemoveField(
            model_name='challengetype',
            name='lastmodifyby',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='lastmodifyby',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='progressionid',
        ),
        migrations.RemoveField(
            model_name='progression',
            name='lastmodifyby',
        ),
        migrations.DeleteModel(
            name='AnswerType',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='ChallengeCurriculum',
        ),
        migrations.DeleteModel(
            name='ChallengeType',
        ),
        migrations.DeleteModel(
            name='Curriculum',
        ),
        migrations.DeleteModel(
            name='Progression',
        ),
    ]
